
package com.heima.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.heima.service.Customer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.heima.com/")
@XmlSeeAlso({
   
})
public interface CustomerService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.heima.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findHasAssocition", targetNamespace = "http://service.heima.com/", className = "com.heima.service.FindHasAssocition")
    @ResponseWrapper(localName = "findHasAssocitionResponse", targetNamespace = "http://service.heima.com/", className = "com.heima.service.FindHasAssocitionResponse")
    public List<Customer> findHasAssocition(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assigncustomerstodecidedzone", targetNamespace = "http://service.heima.com/", className = "com.heima.service.Assigncustomerstodecidedzone")
    @ResponseWrapper(localName = "assigncustomerstodecidedzoneResponse", targetNamespace = "http://service.heima.com/", className = "com.heima.service.AssigncustomerstodecidedzoneResponse")
    public void assigncustomerstodecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<com.heima.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findNotAssocition", targetNamespace = "http://service.heima.com/", className = "com.heima.service.FindNotAssocition")
    @ResponseWrapper(localName = "findNotAssocitionResponse", targetNamespace = "http://service.heima.com/", className = "com.heima.service.FindNotAssocitionResponse")
    public List<Customer> findNotAssocition();

    /**
     * 
     * @return
     *     returns java.util.List<com.heima.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.heima.com/", className = "com.heima.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.heima.com/", className = "com.heima.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDecidedzoneIdByAdderss", targetNamespace = "http://service.heima.com/", className = "com.heima.service.FindDecidedzoneIdByAdderss")
    @ResponseWrapper(localName = "findDecidedzoneIdByAdderssResponse", targetNamespace = "http://service.heima.com/", className = "com.heima.service.FindDecidedzoneIdByAdderssResponse")
    public String findDecidedzoneIdByAdderss(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.heima.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelphone", targetNamespace = "http://service.heima.com/", className = "com.heima.service.FindCustomerByTelphone")
    @ResponseWrapper(localName = "findCustomerByTelphoneResponse", targetNamespace = "http://service.heima.com/", className = "com.heima.service.FindCustomerByTelphoneResponse")
    public Customer findCustomerByTelphone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
